### ISSUE TITLE
Peer Review # 2

### ISSUE THREAD

**Issue by bfleurence** [jfhasj/mlb_lahman_analysis#3]
**Summary**
This paper does a good job of measuring different metrics and using multiple regression to analyze their impact on a team's winning percentage. Specifically, looking at ERA, runs per game, hits per 9 innings, and the number of stolen bases. 
**Strong positive points:**
- I really like the graphs and the way the data is presented
- The structure of your paper is sound 
- Findings and analysis are made clear at the end of the paper 
**Critical improvements needed:**
- Lurking variables such as injuries and spending power should be discussed similarly to how the rules changes were in section 3.8. 
- Discussion about ERA and Runs scored is a little surface level; I would like to see a more in-depth analysis on balancing the two aspects and whether teams should focus on one more than the other. 
**Suggestions for improvement:**
- I think your graphs are really strong, so adding more throughout the paper can help readers visualize your data better 
- Expand on the discussion and effects of the parameters 
- Include more analysis on potential lurking variables 

**Evaluation:**
R/Python cited (1/1 pts)
Data cited (1/1 pts)
Class paper (1/1 pts)
LLM documentation (1/1 pts)
Title (2/2 pts)
Author, date, and repo (2/2 pts)
Abstract (4/4 pts)
Introduction (4/4 pts)
Estimand (1/1 pts)
Data (10/10 pts)
Measurement (4/4 pts)
Model (10/10 pts)
Results ([Mark]/10 pts)
[Comment]
Discussion (5/10 pts)
- Deeper analysis of the variables, specifically era and runs per game, can be made.  
Prose (5/6 pts)
Cross-references (1/1 pts)
Captions 2/2 pts)
Graphs/tables/etc (3/4 pts)
- The graphs are good, I would add more. 
Surveys, sampling, and observational data appendix (4/10 pts)
- first table in appendix is good 
- outline for A.2 and A.3 are promising areas of discussion, simply need to be filled out. 
Referencing (4/4 pts)
Commits (2/2 pts)
Sketches (2/2 pts)
Simulation (4/4 pts)
Tests (4/4 pts)
Parquet (1/1 pts)
Reproducible workflow (4/4 pts)
Enhancements (4/4 pts)
Miscellaneous (3/3 pts)
Estimated overall mark:
95 out of 108.
Any other comments:
The paper is well written and interesting; taking your analysis a little further by discussing more in-depth the relationship between your model parameters as well as other lurking variables, would further increase the strength of this essay.

**Comment by seanc873** [comment]
Thanks for the comment!
